#!/bin/bash
lines=(
Andromeda_lines
Aquarius_lines
Aquila_lines
Boötes_lines
Camelopardalis_lines
Canes_Venatici_lines
Capricornus_lines
Cassiopeia_lines
Cepheus_lines
Coma_Berenices_lines
Corona_Borealis_lines
Cygnus_lines
Delphinus_lines
Draco_lines
Equuleus_lines
Hercules_lines
Lacerta_lines
Leo_Minor_lines
Libra_lines
Lynx_lines
Lyra_lines
Ophiuchus_lines
Pegasus_lines
Perseus_lines
Sagitta_lines
Sagittarius_lines
Scorpius_lines
Scutum_lines
Serpens_caput_lines
Serpens_cauda_lines
Triangulum_lines
Ursa_Major_full_lines
Ursa_Minor_lines
Virgo_lines
Vulpecula_lines

/borders/Andromeda_lines
/borders/Aquarius_lines
/borders/Aquila_lines
/borders/Boötes_lines
/borders/Camelopardalis_lines
/borders/Canes_Venatici_lines
/borders/Capricornus_lines
/borders/Cassiopeia_lines
/borders/Cepheus_lines
/borders/Coma_Berenices_lines
/borders/Corona_Borealis_lines
/borders/Cygnus_lines
/borders/Delphinus_lines
/borders/Draco_lines
/borders/Equuleus_lines
/borders/Hercules_lines
/borders/Lacerta_lines
/borders/Leo_Minor_lines
/borders/Libra_lines
/borders/Lynx_lines
/borders/Lyra_lines
/borders/Ophiuchus_lines
/borders/Pegasus_lines
/borders/Perseus_lines
/borders/Sagitta_lines
/borders/Sagittarius_lines
/borders/Scorpius_lines
/borders/Scutum_lines
/borders/Serpens_caput_lines
/borders/Serpens_cauda_lines
/borders/Triangulum_lines
/borders/Ursa_Major_full_lines
/borders/Ursa_Minor_lines
/borders/Virgo_lines
/borders/Vulpecula_lines
)