#!/bin/bash

header="Name,Right Ascension,Declination,Apparent Magnitude,Constellation"

constellations=(
    # "Ursa Major"
    # "Ursa Minor"
    # "Cassiopeia"
    # "Cepheus"
    # "Pegasus"
    # "Perseus"
    # "Orion"
    # "Boötes"
    # "Auriga"
    # "Andromeda"
    # "Coma Berenices"
    # "Hercules"
    # "Corona Borealis"
    # "Lyra"
    # "Cygnus"
    # "Aquila"
    # "Serpens"
    # "Delphinus"
    # "Hydra"
    # "Canes Venatici"
    # "Leo Minor"
    # "Lynx"
    # "Camelopardalis"
    # "Monoceros"
    # "Corvus"
    # "Crater"
    # "Sextans"
    # "Ophiuchus"
    # "Sagittarius"
    # "Lacerta"
    # "Triangulum"
    # "Sagitta"
    # "Canis Minor"
    # "Aquarius"
    # "Aries"
    # "Cancer"
    # "Capricornus"
    # "Draco"
    # "Gemini"
    # "Leo"
    # "Libra"
    # "Pisces"
    # "Scorpius"
    # "Taurus"
    # "Virgo"
    "Canis Major"
    "Equuleus"
    "Vulpecula"
    "Scutum"
    "Piscis Austrinus"
    "Sculptor"
    "Cetus"
    "Eridanus"
    "Fornax"
    "Circinus"
    "Antlia"
    "Puppis"
    "Grus"
    "Lepus"
    "Phoenix"
    "Corona Australis"
    "Telescopium"
    "Caelum"
    "Columba"
    "Pyxis"
    "Lupus"
    "Microscopium"
    "Centaurus"
    "Crux"
    "Vela"
    "Carina"
    "Pictor"
    "Dorado"
    "Horologium"
    "Reticulum"
    "Tucana"
    "Indus"
    "Pavo"
    "Ara"
    "Norma"
    "Triangulum Australe"
    "Musca"
    "Volans"
    "Mensa"
    "Hydrus"
    "Octans"
    "Apus"
    "Chamaeleon"
)

for constellation in "${constellations[@]}"; do

    filename="${constellation// /_}"
    file=./zodiac/constellations/${filename}_0.csv

    rm $file
    echo $header >> $file
    cat constellations.csv | grep "$constellation" >> $file

done