#!/bin/bash
borders=(
combined_Delphinus_Equuleus_borders
combined_Sagitta_Vulpecula_borders
Combined_Scutum_Serpens_cauda_borders
combined_Columba_caelum_borders
combined_Monoceros_Canis_minor_borders
Antlia_borders
Andromeda_borders
Aquarius_borders
Aquila_borders
Ara_borders
Aries_borders
Auriga_borders
Boötes_borders
# Caelum_borders
Cancer_borders
Canes_Venatici_borders
Canis_Major_borders
# Canis_Minor_borders
Capricornus_borders
# Carina_borders
Centaurus_borders
Cetus_borders
# Circinus_borders
# Columba_borders
Coma_Berenices_borders
Corona_Australis_borders
Corona_Borealis_borders
Corvus_borders
Crater_borders
Cygnus_borders
# Delphinus_borders
# Dorado_borders
# Equuleus_borders
Eridanus_borders
Fornax_borders
Gemini_borders
Grus_borders
Hercules_borders
Horologium_borders
Hydra_borders
# Indus_borders
Lacerta_borders
Leo_borders
Leo_Minor_borders
Lepus_borders
Libra_borders
Lupus_borders
Lynx_borders
Lyra_borders
Microscopium_borders
# Monoceros_borders
Norma_borders
Ophiuchus_borders
Orion_borders
Pegasus_borders
Perseus_borders
Phoenix_borders
Pictor_borders
Pisces_borders
Piscis_Austrinus_borders
Puppis_borders
Pyxis_borders
Reticulum_borders
# Sagitta_borders
Sagittarius_borders
Scorpius_borders
Sculptor_borders
# Scutum_borders
Serpens_caput_borders
# Serpens_cauda_borders
Sextans_borders
Taurus_borders
Telescopium_borders
Triangulum_borders
# Tucana_borders
Vela_borders
Virgo_borders
# Volans_borders
# Vulpecula_borders
)
