#!/bin/bash
lines=(
./borders/Andromeda_borders
./borders/Antlia_borders
./borders/Aquarius_borders
./borders/Aquila_borders
./borders/Aries_borders
./borders/Auriga_borders
./borders/Boötes_borders
./borders/Camelopardalis_borders
./borders/Cancer_borders
./borders/Canes_Venatici_borders
./borders/Canis_Major_borders
./borders/Canis_Minor_borders
./borders/Capricornus_borders
./borders/Cassiopeia_borders
./borders/Cepheus_borders
./borders/Cetus_borders
./borders/Coma_Berenices_borders
./borders/Corona_Australis_borders
./borders/Corona_Borealis_borders
./borders/Corvus_borders
./borders/Crater_borders
./borders/Cygnus_borders
./borders/Delphinus_borders
./borders/Draco_borders
./borders/Equuleus_borders
./borders/Eridanus_borders
./borders/Fornax_borders
./borders/Gemini_borders
./borders/Hercules_borders
./borders/Hydra_borders
./borders/Lacerta_borders
./borders/Leo_borders
./borders/Leo_Minor_borders
./borders/Lepus_borders
./borders/Libra_borders
./borders/Lynx_borders
./borders/Lyra_borders
./borders/Microscopium_borders
./borders/Monoceros_borders
./borders/Ophiuchus_borders
./borders/Orion_borders
./borders/Pegasus_borders
./borders/Perseus_borders
./borders/Pisces_borders
./borders/Piscis_Austrinus_borders
./borders/Pyxis_borders
./borders/Sagitta_borders
./borders/Sagittarius_borders
./borders/Scorpius_borders
./borders/Sculptor_borders
./borders/Scutum_borders
./borders/Serpens_caput_borders
./borders/Serpens_cauda_borders
./borders/Sextans_borders
./borders/Taurus_borders
./borders/Telescopium_borders
./borders/Triangulum_borders
./borders/Ursa_Major_full_borders
./borders/Ursa_Minor_borders
./borders/Virgo_borders
./borders/Vulpecula_borders
)