[Planet]
axial_tilt = 23.5047 # [deg] around x axis
Day_len = 24    #[hour] Length of a solar day
Year_len = 365.2422
YEAR = 2023

[Location]
Name = "HOME"
GeoLat = 47.208075    # [deg]
GeoLon = 18.372626   # [deg]
GMT = 1     # [Hour]

[Wall]
WallAzmt = 9    # [deg], right side is free
WallInc = 0   #[deg] angle realtive to vertcal. 90 is horizontal flat

[Plot]
xlim = [-4.0, 4.0]
ylim = [-4.0, 2.0]
Anal_Hours = [4, 5, 6, 7, 8]
arrow_dates = [50, 120, 200]

[SprEq]     #[sec] 2023. 03. 20. 22:24
day = 78
hour = 22
min = 24